### ISSUE TITLE
App rpath is "blank" mkdir: : No such file or directory

### ISSUE THREAD

**Issue by teelekkung** [Al4ise/Azule#69]
sahakiyat@sahakiyats-air ~ % azule -i Downloads/com.spotify.client.ipa -o Downloads -v -w -f Desktop/Spotilife.dylib Desktop/Volify.dylib 
iPA will be written to /Users/sahakiyat/Downloads/com.spotify.client.ipa+Spotilife.dylib+Volify.dylib.ipa
/var/folders/tn/b415gdgd3510xkbj74tzwmj00000gn/T/tmp.N44CjxEa/5278/Tweak has been created
Path to iPA is /Users/sahakiyat/Downloads/com.spotify.client.ipa
Extracting iPA...
IPA extracted
Removing Watch App...
Removed Watch App
App executable is Payload/Spotify.app/Spotify
App rpath is 
mkdir: : No such file or directory
/Users/sahakiyat/Desktop/Spotilife.dylib will be imported
Copied Spotilife.dylib to work directory
/Users/sahakiyat/Desktop/Volify.dylib will be imported
Copied Volify.dylib to work directory
Copied Spotilife.dylib to app directory
Copied Volify.dylib to app directory
Couldn't strip codesign from Spotilife.dylib

MacOS 11.6.3 
I do "git checkout 577d4ce81a4ffdff2888ad8872c64f65028e490b" to see if it has the same problem , and the answer is it doesn't

**Comment by teelekkung** [comment]
and also I have a problem where app after inject and sideload. it crash on lunch. ipa generate fine no error report. I use sideloadly to side load my ipa.
I can confirm that my ipa is fine because when I use injectipa (https://github.com/Netskao/MacOS-Utils) it work fine and can side load normally and I use bagbak (https://github.com/ChiChou/bagbak) to get my ipa from my jail device

**Comment by Al4ise** [comment]
I just tried it with a fresh copy of spotify, decrypted with flexdecrypt, and no such issues came up. Could you send me the ipa you used?

**Comment by teelekkung** [comment]
here log from 577d4ce81a4ffdff2888ad8872c64f65028e490b and my device when open Spotify [log.txt](https://github.com/Al4ise/Azule/files/7741264/log.txt)
here my ipa [com.spotify.client.ipa](https://f000.backblazeb2.com/file/Teelekkung/com.spotify.client.ipa)
here my dylib [Volify.dylib](https://f000.backblazeb2.com/file/Teelekkung/Volify.dylib), [Spotilife.dylib](https://f000.backblazeb2.com/file/Teelekkung/Spotilife.dylib)
here my ipa out from Azule [com.spotify.client.ipa+Volify.dylib+Spotilife.dylib.ipa](https://f000.backblazeb2.com/file/Teelekkung/com.spotify.client.ipa%2BVolify.dylib%2BSpotilife.dylib.ipa)

**Comment by Ditpo** [comment]
I got the same issue with "mkdir: : No such file or directory" and "Couldn't strip codesign from tweak"
Happens with all tweaks since today. Since this issue was opened just yesterday, I suspect this is something new.

Help or a fix would be greatly appreciated

**Comment by Al4ise** [comment]
should be fixed now, sorry I took so long

**Comment by Ditpo** [comment]
Thank you very much for that! It wasn’t long at all :)

**Comment by teelekkung** [comment]
that wasn’t long at all , compared to another developer that I have I commit issue to you are the fastest that I ever met , And After I try rpath is now fix but for some reason app still crash on lunch again

**Comment by Al4ise** [comment]
And it doesnt crash with injectipa?

**Comment by teelekkung** [comment]
no , with injectipa everything work fine

**Comment by teelekkung** [comment]
oh just finding this new, in Frameworks folder it has all the dylib to inject but in executable itself (I use hex fiend to look at executable. )it only has one dylib inject which is volify.dylib at the bottom of what i can read , lower than that I can't read , 

here is that last part [ ( @executable_path/Frameworks ) .*. .|. 0% .0 @rpath/Volify.dylib ]

when I search for texts substrate, substitute, CydiaSubstrate.framework , there were non be found

**Comment by Al4ise** [comment]
I figured out what the issue is exactly but I may take some time to solve it

**Comment by teelekkung** [comment]
Thank you , that is my pleasure helping find the issue

**Comment by Al4ise** [comment]
should be fixed now

**Comment by teelekkung** [comment]
SHEESH! that work like a boom . Thank you , Thank you very much ,I appreciate your work

**Comment by teelekkung** [comment]
SHEESH! that work like a boom . Thank you , Thank you very much ,I appreciate your work
